<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'code' => 'PSH001AMM001',
                'name' => 'Oversize Shirt',
                'price' => 125000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'M',
                'color' => '#A6B9B7',
                'image' => 'Group_17.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH001ELL001',
                'name' => 'Oversize Shirt',
                'price' => 125000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'L',
                'color' => '#E6B9A6',
                'image' => 'Group_17.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH001ELL004',
                'name' => 'Oversize Shirt',
                'price' => 125000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'L',
                'color' => '#E6B9A6',
                'image' => 'Group_17.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH001AXL001',
                'name' => 'Oversize Shirt',
                'price' => 125000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#A6B9B7',
                'image' => 'Group_17.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH0028SS001',
                'name' => 'Polo Shirt',
                'price' => 153000,
                'desc' => 'Kaos lengan pendek dengan yang nyaman saat di gunakan.',
                'size' => 'S',
                'color' => '#858374',
                'image' => 'Group_18.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH002FLL001',
                'name' => 'Polo Shirt',
                'price' => 153000,
                'desc' => 'Kaos lengan pendek dengan yang nyaman saat di gunakan.',
                'size' => 'L',
                'color' => '#FF4191',
                'image' => 'Group_18.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH0029XL001',
                'name' => 'Polo Shirt',
                'price' => 153000,
                'desc' => 'Kaos lengan pendek dengan yang nyaman saat di gunakan.',
                'size' => 'XL',
                'color' => '#96C9F4',
                'image' => 'Group_18.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH001AMM002',
                'name' => 'Oversize Shirt',
                'price' => 125000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'M',
                'color' => '#A6B9B7',
                'image' => 'casual_shirt.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH001ELL002',
                'name' => 'Oversize Shirt',
                'price' => 125000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'L',
                'color' => '#E6B9A6',
                'image' => 'casual_shirt.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH0028SS002',
                'name' => 'Polo Shirt',
                'price' => 153000,
                'desc' => 'Kaos lengan pendek dengan yang nyaman saat di gunakan.',
                'size' => 'S',
                'color' => '#858374',
                'image' => 'Group_18.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH002FLL002',
                'name' => 'Polo Shirt',
                'price' => 153000,
                'desc' => 'Kaos lengan pendek dengan yang nyaman saat di gunakan.',
                'size' => 'L',
                'color' => '#FF4191',
                'image' => 'Group_18.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH003AXL001',
                'name' => 'Sport Shirt',
                'price' => 120000,
                'desc' => 'Sport shirt dengan breathable fabric.',
                'size' => 'XL',
                'color' => '#A6B9B7',
                'image' => 'Group_19.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH003BXS001',
                'name' => 'Sport Shirt',
                'price' => 120000,
                'desc' => 'Sport shirt dengan breathable fabric.',
                'size' => 'XS',
                'color' => '#E6B9A6',
                'image' => 'Group_19.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH002CSS001',
                'name' => 'Polo Shirt',
                'price' => 153000,
                'desc' => 'Kaos lengan pendek dengan yang nyaman saat di gunakan.',
                'size' => 'S',
                'color' => '#96C9F4',
                'image' => 'Group_18.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH002DMM001',
                'name' => 'Polo Shirt',
                'price' => 153000,
                'desc' => 'Kaos lengan pendek dengan yang nyaman saat di gunakan.',
                'size' => 'M',
                'color' => '#FF4191',
                'image' => 'Group_18.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH001ELL003',
                'name' => 'Oversize Shirt',
                'price' => 125000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'L',
                'color' => '#858374',
                'image' => 'casual_shirt.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH001AXL002',
                'name' => 'Oversize Shirt',
                'price' => 125000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#A6B9B7',
                'image' => 'casual_shirt.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH004AXL001',
                'name' => 'Basic Shirt',
                'price' => 199000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#a49c7c',
                'image' => 'Group_63.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH0056XL001',
                'name' => 'Green Shirt',
                'price' => 289000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#686c59',
                'image' => 'Group_62.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSH006DXL001',
                'name' => 'Oversize Shirt',
                'price' => 299000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#d8d3ad',
                'image' => 'Group_61.png',
                'type' => 'shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'POU0019XL001',
                'name' => 'Cardigan',
                'price' => 89000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#9a7e74',
                'image' => 'Group_26.png',
                'type' => 'outerwear',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'POU002BXL001',
                'name' => 'Classic Cardigan',
                'price' => 99000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#b6b3b3',
                'image' => 'Group_27.png',
                'type' => 'outerwear',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'POU003FXL001',
                'name' => 'Stripe Sweater',
                'price' => 199998,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#f5f5f3',
                'image' => 'Group_28.png',
                'type' => 'outerwear',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'POU004DXL001',
                'name' => 'Stripe Sweater',
                'price' => 199998,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#d8e3f5',
                'image' => 'Group_49.png',
                'type' => 'outerwear',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'POU005FXL001',
                'name' => 'Classic Cardigan',
                'price' => 99000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#ffecb6',
                'image' => 'Group_48.png',
                'type' => 'outerwear',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'POU0065XL001',
                'name' => 'Cardigan',
                'price' => 89000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#51403b',
                'image' => 'Group_47.png',
                'type' => 'outerwear',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PTS0018XL001',
                'name' => 'Mini T-shirt',
                'price' => 299000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#8e3d30',
                'image' => 'Group_50.png',
                'type' => 'tshirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PTS0022XL001',
                'name' => 'Linen T-Shirt',
                'price' => 254000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#292c3e',
                'image' => 'Group_51.png',
                'type' => 'tshirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PTS003FXL001',
                'name' => 'Long Stripe T-Shirt',
                'price' => 499000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#f3f3fa',
                'image' => 'Group_52.png',
                'type' => 'tshirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PTS004DXL001',
                'name' => 'Mini T-shirt',
                'price' => 299000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#d3d9f0',
                'image' => 'Group_53.png',
                'type' => 'tshirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PTS005EXL001',
                'name' => 'Long Stripe T-Shirt',
                'price' => 499000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#eceaf4',
                'image' => 'Group_52.png',
                'type' => 'tshirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PTS006FXL001',
                'name' => 'Linen T-Shirt',
                'price' => 254000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#f49c8f',
                'image' => 'Group_54.png',
                'type' => 'tshirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PPA0013XL001',
                'name' => 'Oversize Jeans',
                'price' => 499999,
                'desc' => 'celana jeans yang enak di pakai.',
                'size' => 'XL',
                'color' => '#354e6e',
                'image' => 'Group_57.png',
                'type' => 'pants',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PPA0027XL001',
                'name' => 'Jogger Pants',
                'price' => 198999,
                'desc' => 'celana polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#7b7c6d',
                'image' => 'Group_56.png',
                'type' => 'pants',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PPA003DXL001',
                'name' => 'Linen Pants',
                'price' => 99999,
                'desc' => 'celana polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#dddcd2',
                'image' => 'Group_58.png',
                'type' => 'pants',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PPA004EXL001',
                'name' => 'Jogger Pants',
                'price' => 198999,
                'desc' => 'celana polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#e1e0d6',
                'image' => 'Group_58.png',
                'type' => 'pants',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PPA0057XL001',
                'name' => 'Linen Pants',
                'price' => 99999,
                'desc' => 'celana polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#745e46',
                'image' => 'Group_55.png',
                'type' => 'pants',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PPA0061XL001',
                'name' => 'Oversize Jeans',
                'price' => 499999,
                'desc' => 'celana jeans yang enak di pakai.',
                'size' => 'XL',
                'color' => '#1b3c5a',
                'image' => 'Group_60.png',
                'type' => 'pants',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PNE001DXL001',
                'name' => 'Square Shirt',
                'price' => 299000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#d3cdc3',
                'image' => 'Group_16.png',
                'type' => 'newarrival',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PNE0023XL001',
                'name' => 'Sabrina Shirt',
                'price' => 99000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#373a41',
                'image' => 'Group_20.png',
                'type' => 'newarrival',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PNE003AXL001',
                'name' => 'Knitted Cardigan',
                'price' => 88000,
                'desc' => 'Kaos polos dengan bahan katun yang enak di pakai.',
                'size' => 'XL',
                'color' => '#a67d59',
                'image' => 'Group_21.png',
                'type' => 'newarrival',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tambahkan data lainnya sesuai kebutuhan
        ];

        // Masukkan data ke dalam tabel products
        foreach ($products as $product) {
            DB::table('products')->insert($product);
        }
    }
}
